X-Zalando-Team: bus
X-Zalando-Type: code

approvals:
  minimum: 2
  from:
    # commenter must be either one of:
    orgs:
      - zalando-stups
    # OR a collaborator of the repo
    collaborators: true
